apiVersion: v1
kind: Service
metadata:
  name: gitlab
  labels:
    name: gitlab
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: ssh
      port: 2222
      targetPort: 2222
      protocol: TCP
  selector:
    name: gitlab
